### ISSUE TITLE
如何将语言更改为简体中文

### ISSUE THREAD

**Issue by hequano** [JustAHuman-xD/SlimefunToEMI#10]
如何将语言更改为简体中文

**Comment by Flamarine** [comment]
Eh this repo is for English only I guess? Also there doesn't seem to be a set of Simplified Chinese translations right now.

额我想这里还是只说英语比较恰当？以及看起来现在还没有简中翻译捏

**Comment by JustAHuman-xD** [comment]
Currently there are PR's open for the translation, however due to a big update that is coming, I have not merged them as most will be changed with that update. After it is done I will merge an updated translation and you will be able to use it translated.

目前有 PR 对翻译开放，但是由于即将到来的大更新，我没有合并它们，因为大多数将随着该更新而改变。 完成后，我将合并更新的翻译，您将能够使用翻译后的翻译。

**Comment by ybw0014** [comment]
TLDR(省流): 等
